# Generated by Django 3.2.7 on 2021-09-11 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstweb', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Userprofile',
        ),
    ]
