# Generated by Django 3.2.7 on 2021-09-16 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstweb', '0003_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Userprofile',
        ),
    ]
