# Generated by Django 3.2.7 on 2021-09-18 09:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('firstweb', '0004_delete_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Followers', models.CharField(max_length=20)),
                ('time', models.CharField(max_length=20)),
                ('No_of_repos', models.IntegerField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Repos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name_of_repo', models.CharField(max_length=100)),
                ('No_of_stars', models.IntegerField()),
                ('owner_of_repo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstweb.profile')),
            ],
        ),
    ]
