# Generated by Django 3.2.7 on 2021-09-18 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstweb', '0005_profile_repos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='No_of_repos',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
